package com.jiebbs.daos;

import com.jiebbs.pojos.Order_item;

public interface Order_itemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insert(Order_item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insertSelective(Order_item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	Order_item selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKeySelective(Order_item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKey(Order_item record);
}