package com.jiebbs.daos;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jiebbs.pojos.Order_item;

public interface Order_itemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insert(Order_item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insertSelective(Order_item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	Order_item selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKeySelective(Order_item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKey(Order_item record);
	
	/**
	 * 根据传入的userId和orderId查询订单中的商品
	 * @param userId
	 * @param orderId
	 * @return
	 */
	List<Order_item> selectByOrderNumAndUserId(@Param("userId")Integer userId,@Param("orderNum")Long orderNum);
	
	/**
	 * 批量插入orderItem
	 * @param orderItemList
	 */
	void benchInsert(List<Order_item> orderItemList);
	
	/**
	 *管理员根据订单号查询用户订单详情 
	 * @param orderNum
	 * @return
	 */
	List<Order_item> selectAllByOrderNum(Long orderNum);
}