package com.jiebbs.daos;

import com.jiebbs.pojos.Pay_info;

public interface Pay_infoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_info_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_info_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insert(Pay_info record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_info_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insertSelective(Pay_info record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_info_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	Pay_info selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_info_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKeySelective(Pay_info record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_info_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKey(Pay_info record);
}