package com.jiebbs.daos;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jiebbs.pojos.Shopping_cart;

public interface Shopping_cartMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insert(Shopping_cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insertSelective(Shopping_cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	Shopping_cart selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKeySelective(Shopping_cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKey(Shopping_cart record);
	
	/**
	 * ﳵ
	 * @param userId
	 * @param productId
	 * @return
	 */
	Shopping_cart selectByUserIdAndProductId(@Param(value="userId")Integer userId,@Param(value="productId")Integer productId);
	
	/**
	 *
	 * @param userId
	 * @return
	 */
	List<Shopping_cart> selectCartByUserId(Integer userId);
	
	/**
	 *
	 * @param userId
	 * @return
	 */
	int selectProductCheckedStatusByUserId(Integer userId);
	
	/**
	 * 
	 * @param userId
	 * @param productIds
	 * @return
	 */
	int delectByUserIdAndProductIds(@Param("userId")Integer userId,@Param("productIds")List<String> productIds);
	
	/**
	 * 
	 * @param userId
	 * @return
	 */
	int checkOrUncheckProduct(@Param("userId")Integer userId,@Param("productId")Integer productId,@Param("checked")Integer checked);
	
	/**
	 * 
	 * @param userId
	 * @return
	 */
	int selectCartProductCount(Integer userId);
	
	/**
	 * 
	 * @param userId
	 * @return
	 */
	 
	List<Shopping_cart> selectCheckedCartByUserId(Integer userId); 
}