package com.jiebbs.daos;

import com.jiebbs.pojos.Shopping_cart;

public interface Shopping_cartMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insert(Shopping_cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int insertSelective(Shopping_cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	Shopping_cart selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKeySelective(Shopping_cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_cart_table
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	int updateByPrimaryKey(Shopping_cart record);
}