package com.jiebbs.pojos;

import java.util.Date;

public class Classification {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification_table.parent_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification_table.name
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification_table.status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification_table.sort_order
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification_table.id
	 * @return  the value of classification_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification_table.id
	 * @param id  the value for classification_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification_table.parent_id
	 * @return  the value of classification_table.parent_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification_table.parent_id
	 * @param parentId  the value for classification_table.parent_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification_table.name
	 * @return  the value of classification_table.name
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification_table.name
	 * @param name  the value for classification_table.name
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification_table.status
	 * @return  the value of classification_table.status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification_table.status
	 * @param status  the value for classification_table.status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification_table.sort_order
	 * @return  the value of classification_table.sort_order
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification_table.sort_order
	 * @param sortOrder  the value for classification_table.sort_order
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification_table.create_time
	 * @return  the value of classification_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification_table.create_time
	 * @param createTime  the value for classification_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification_table.update_time
	 * @return  the value of classification_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification_table.update_time
	 * @param updateTime  the value for classification_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}