package com.jiebbs.pojos;

import java.math.BigDecimal;
import java.util.Date;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.order_no
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Long orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.user_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.shipping_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer shippingId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.payment
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private BigDecimal payment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.payment_type
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer paymentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.postage
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer postage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.payment_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date paymentTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.send_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date sendTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.end_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.close_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date closeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.id
	 * @return  the value of order_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.id
	 * @param id  the value for order_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.order_no
	 * @return  the value of order_table.order_no
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Long getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.order_no
	 * @param orderNo  the value for order_table.order_no
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.user_id
	 * @return  the value of order_table.user_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.user_id
	 * @param userId  the value for order_table.user_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.shipping_id
	 * @return  the value of order_table.shipping_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getShippingId() {
		return shippingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.shipping_id
	 * @param shippingId  the value for order_table.shipping_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setShippingId(Integer shippingId) {
		this.shippingId = shippingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.payment
	 * @return  the value of order_table.payment
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public BigDecimal getPayment() {
		return payment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.payment
	 * @param payment  the value for order_table.payment
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPayment(BigDecimal payment) {
		this.payment = payment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.payment_type
	 * @return  the value of order_table.payment_type
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getPaymentType() {
		return paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.payment_type
	 * @param paymentType  the value for order_table.payment_type
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPaymentType(Integer paymentType) {
		this.paymentType = paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.status
	 * @return  the value of order_table.status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.status
	 * @param status  the value for order_table.status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.postage
	 * @return  the value of order_table.postage
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getPostage() {
		return postage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.postage
	 * @param postage  the value for order_table.postage
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPostage(Integer postage) {
		this.postage = postage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.payment_time
	 * @return  the value of order_table.payment_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getPaymentTime() {
		return paymentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.payment_time
	 * @param paymentTime  the value for order_table.payment_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPaymentTime(Date paymentTime) {
		this.paymentTime = paymentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.send_time
	 * @return  the value of order_table.send_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.send_time
	 * @param sendTime  the value for order_table.send_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.end_time
	 * @return  the value of order_table.end_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.end_time
	 * @param endTime  the value for order_table.end_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.close_time
	 * @return  the value of order_table.close_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getCloseTime() {
		return closeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.close_time
	 * @param closeTime  the value for order_table.close_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.create_time
	 * @return  the value of order_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.create_time
	 * @param createTime  the value for order_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_table.update_time
	 * @return  the value of order_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_table.update_time
	 * @param updateTime  the value for order_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}