package com.jiebbs.pojos;

import java.math.BigDecimal;
import java.util.Date;

public class Order_item {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.user_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.order_no
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Long orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.product_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.product_name
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.product_image
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String productImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.current_unit_price
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private BigDecimal currentUnitPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.quatity
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer quatity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.total_price
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private BigDecimal totalPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.id
	 * @return  the value of order_item_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.id
	 * @param id  the value for order_item_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.user_id
	 * @return  the value of order_item_table.user_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.user_id
	 * @param userId  the value for order_item_table.user_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.order_no
	 * @return  the value of order_item_table.order_no
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Long getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.order_no
	 * @param orderNo  the value for order_item_table.order_no
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.product_id
	 * @return  the value of order_item_table.product_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.product_id
	 * @param productId  the value for order_item_table.product_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.product_name
	 * @return  the value of order_item_table.product_name
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.product_name
	 * @param productName  the value for order_item_table.product_name
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.product_image
	 * @return  the value of order_item_table.product_image
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getProductImage() {
		return productImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.product_image
	 * @param productImage  the value for order_item_table.product_image
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setProductImage(String productImage) {
		this.productImage = productImage == null ? null : productImage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.current_unit_price
	 * @return  the value of order_item_table.current_unit_price
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public BigDecimal getCurrentUnitPrice() {
		return currentUnitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.current_unit_price
	 * @param currentUnitPrice  the value for order_item_table.current_unit_price
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setCurrentUnitPrice(BigDecimal currentUnitPrice) {
		this.currentUnitPrice = currentUnitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.quatity
	 * @return  the value of order_item_table.quatity
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getQuatity() {
		return quatity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.quatity
	 * @param quatity  the value for order_item_table.quatity
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setQuatity(Integer quatity) {
		this.quatity = quatity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.total_price
	 * @return  the value of order_item_table.total_price
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public BigDecimal getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.total_price
	 * @param totalPrice  the value for order_item_table.total_price
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.create_time
	 * @return  the value of order_item_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.create_time
	 * @param createTime  the value for order_item_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item_table.update_time
	 * @return  the value of order_item_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item_table.update_time
	 * @param updateTime  the value for order_item_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}