package com.jiebbs.pojos;

import java.util.Date;

public class Pay_info {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_info_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_info_table.user_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_info_table.order_no
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Long orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_info_table.pay_platform
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer payPlatform;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_info_table.platform_number
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String platformNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_info_table.platform_status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String platformStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_info_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_info_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_info_table.id
	 * @return  the value of pay_info_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_info_table.id
	 * @param id  the value for pay_info_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_info_table.user_id
	 * @return  the value of pay_info_table.user_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_info_table.user_id
	 * @param userId  the value for pay_info_table.user_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_info_table.order_no
	 * @return  the value of pay_info_table.order_no
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Long getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_info_table.order_no
	 * @param orderNo  the value for pay_info_table.order_no
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_info_table.pay_platform
	 * @return  the value of pay_info_table.pay_platform
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getPayPlatform() {
		return payPlatform;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_info_table.pay_platform
	 * @param payPlatform  the value for pay_info_table.pay_platform
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPayPlatform(Integer payPlatform) {
		this.payPlatform = payPlatform;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_info_table.platform_number
	 * @return  the value of pay_info_table.platform_number
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getPlatformNumber() {
		return platformNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_info_table.platform_number
	 * @param platformNumber  the value for pay_info_table.platform_number
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPlatformNumber(String platformNumber) {
		this.platformNumber = platformNumber == null ? null : platformNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_info_table.platform_status
	 * @return  the value of pay_info_table.platform_status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getPlatformStatus() {
		return platformStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_info_table.platform_status
	 * @param platformStatus  the value for pay_info_table.platform_status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPlatformStatus(String platformStatus) {
		this.platformStatus = platformStatus == null ? null : platformStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_info_table.create_time
	 * @return  the value of pay_info_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_info_table.create_time
	 * @param createTime  the value for pay_info_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_info_table.update_time
	 * @return  the value of pay_info_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_info_table.update_time
	 * @param updateTime  the value for pay_info_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}