package com.jiebbs.pojos;

import java.math.BigDecimal;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.category_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.name
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.subtitle
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String subtitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.main_image
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String mainImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.sub_image
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String subImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.detail
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.price
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.stock
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer stock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.id
	 * @return  the value of product_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.id
	 * @param id  the value for product_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.category_id
	 * @return  the value of product_table.category_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.category_id
	 * @param categoryId  the value for product_table.category_id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.name
	 * @return  the value of product_table.name
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.name
	 * @param name  the value for product_table.name
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.subtitle
	 * @return  the value of product_table.subtitle
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getSubtitle() {
		return subtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.subtitle
	 * @param subtitle  the value for product_table.subtitle
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle == null ? null : subtitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.main_image
	 * @return  the value of product_table.main_image
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getMainImage() {
		return mainImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.main_image
	 * @param mainImage  the value for product_table.main_image
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setMainImage(String mainImage) {
		this.mainImage = mainImage == null ? null : mainImage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.sub_image
	 * @return  the value of product_table.sub_image
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getSubImage() {
		return subImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.sub_image
	 * @param subImage  the value for product_table.sub_image
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setSubImage(String subImage) {
		this.subImage = subImage == null ? null : subImage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.detail
	 * @return  the value of product_table.detail
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.detail
	 * @param detail  the value for product_table.detail
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setDetail(String detail) {
		this.detail = detail == null ? null : detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.price
	 * @return  the value of product_table.price
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.price
	 * @param price  the value for product_table.price
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.stock
	 * @return  the value of product_table.stock
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getStock() {
		return stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.stock
	 * @param stock  the value for product_table.stock
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setStock(Integer stock) {
		this.stock = stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.status
	 * @return  the value of product_table.status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.status
	 * @param status  the value for product_table.status
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.create_time
	 * @return  the value of product_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.create_time
	 * @param createTime  the value for product_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime == null ? null : createTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_table.update_time
	 * @return  the value of product_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_table.update_time
	 * @param updateTime  the value for product_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime == null ? null : updateTime.trim();
	}
}