package com.jiebbs.pojos;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.username
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.password
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.email
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.phone
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.question
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String question;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.answer
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private String answer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.role
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Integer role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.id
	 * @return  the value of user_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.id
	 * @param id  the value for user_table.id
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.username
	 * @return  the value of user_table.username
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.username
	 * @param username  the value for user_table.username
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.password
	 * @return  the value of user_table.password
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.password
	 * @param password  the value for user_table.password
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.email
	 * @return  the value of user_table.email
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.email
	 * @param email  the value for user_table.email
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.phone
	 * @return  the value of user_table.phone
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.phone
	 * @param phone  the value for user_table.phone
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.question
	 * @return  the value of user_table.question
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getQuestion() {
		return question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.question
	 * @param question  the value for user_table.question
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setQuestion(String question) {
		this.question = question == null ? null : question.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.answer
	 * @return  the value of user_table.answer
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public String getAnswer() {
		return answer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.answer
	 * @param answer  the value for user_table.answer
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setAnswer(String answer) {
		this.answer = answer == null ? null : answer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.role
	 * @return  the value of user_table.role
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.role
	 * @param role  the value for user_table.role
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.create_time
	 * @return  the value of user_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.create_time
	 * @param createTime  the value for user_table.create_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_table.update_time
	 * @return  the value of user_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_table.update_time
	 * @param updateTime  the value for user_table.update_time
	 * @mbg.generated  Sat Jul 21 15:36:47 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}